site_name: yardb
repo_url: http://github.com/jose-gilberto/yardb
docs_dir: docsrc
site_dir: docs
nav:
    - Home: index.md
    - Architecture: explanation.md
    - Internals:
      - Getting Started: gettingstarted.md
      - Utils: utils.md
      - Metadata & Indexes: metadata.md
    - Informations:
      - Patch Notes: patch-notes.md
theme: readthedocs