site_name: yardb
repo_url: http://github.com/jose-gilberto/yardb
docs_dir: docsrc
site_dir: docs
nav:
    - Home: index.md
    - Architecture: explanation.md
    - Internals:
      - Getting Started: gettingstarted.md
      - Metadata & Indexes: metadata.md
      - Decoding: decoding.md
      - Desktop Usage: desktop.md
      - How It Works: howitworks.md
      - Multinode: multinode.md
      - Sharding: sharding.md
      - Sources: sources.md
      - Writing: writing.md
      - Video Loading: video-loading-example.md
    - Dataset Conversions:
      - Falling Things: convert-falling-things.md
      - Objectron: convert-objectron.md
theme: readthedocs